EVENT_TIANX_YHSX.TITLE = "aafasdfsdf"
EVENT_TIANX_YHSX.DESC  = "sdfasdlf%s%s"
EVENT_TIANX_YHSX.option1.DESC = "OK"

EVENT_TIANX_YHSX_END.TITLE  = "EVENT_TIANX_YHSX_END.TITLE"
EVENT_TIANX_YHSX_END.DESC   = "EVENT_TIANX_YHSX_END.DESC"
EVENT_TIANX_YHSX_END.option1.DESC = "option1"

EVENT_STAB_DEC.TITLE = "EVENT_STAB_DEC.TITLE"
EVENT_STAB_DEC.DESC = "EVENT_STAB_DEC.DESC"
EVENT_STAB_DEC.option1.DESC = "option1"

EVENT_STAB_INC.TITLE = "EVENT_STAB_INC.TITLE"
EVENT_STAB_INC.DESC = "EVENT_STAB_INC.DESC"
EVENT_STAB_INC.option1.DESC = "option1"

EVENT_TIANX_YHSX_JQ1.TITLE = "EVENT_TIANX_YHSX_JQ1.TITLE"
EVENT_TIANX_YHSX_JQ1.DESC = "EVENT_TIANX_YHSX_JQ1.DESC"
EVENT_TIANX_YHSX_JQ1.option1.DESC = "option1"
EVENT_TIANX_YHSX_JQ1.option2.DESC = "option2%s"
EVENT_TIANX_YHSX_JQ1.option3.DESC = "option3"

EVENT_EMP_HEATH_DEC.TITLE = "EVENT_EMP_HEATH_DEC.TITLE"
EVENT_EMP_HEATH_DEC.DESC = "EVENT_EMP_HEATH_DEC.DESC"
EVENT_EMP_HEATH_DEC.option1.DESC = "option1"

EVENT_EMP_HEATH_INC.TITLE = "EVENT_EMP_HEATH_INC.TITLE"
EVENT_EMP_HEATH_INC.DESC = "EVENT_EMP_HEATH_INC.DESC"
EVENT_EMP_HEATH_INC.option1.DESC = "option1"

EVENT_EMP_DIE.TITLE = "EVENT_EMP_DIE.TITLE"
EVENT_EMP_DIE.DESC = "EVENT_EMP_DIE.DESC"
EVENT_EMP_DIE.option1.DESC = "option1"

EVENT_SG_ILL_RESIGN.TITLE = "EVENT_SG_ILL_RESIGN.TITLE"
EVENT_SG_ILL_RESIGN.DESC = "EVENT_SG_ILL_RESIGN.DESC"
EVENT_SG_ILL_RESIGN.option1.DESC = "option1"

EVENT_SG_SUICDIE.TITLE = "EVENT_SG_SUICDIE.TITLE"
EVENT_SG_SUICDIE.DESC = "EVENT_SG_SUICDIE.DESC"
EVENT_SG_SUICDIE.option1.DESC = "option1"

EVENT_SG_EMPTY.TITLE = "EVENT_SG_EMPTY.TITLE"
EVENT_SG_EMPTY.DESC = "EVENT_SG_EMPTY.DESC"
EVENT_SG_EMPTY.option1.DESC = "option1%s"
EVENT_SG_EMPTY.option2.DESC = "option2%s"
EVENT_SG_EMPTY.option3.DESC = "option3%s"

EVENT_JQ_EMPTY.TITLE = "EVENT_JQ_EMPTY.TITLE"
EVENT_JQ_EMPTY.DESC = "EVENT_JQ_EMPTY.DESC"
EVENT_JQ_EMPTY.option1.DESC = "option1%s"
EVENT_JQ_EMPTY.option2.DESC = "option2%s"
EVENT_JQ_EMPTY.option3.DESC = "option3%s"

EVENT_CS_EMPTY.TITLE = "EVENT_CS_EMPTY.TITLE"
EVENT_CS_EMPTY.DESC = "EVENT_CS_EMPTY.DESC"
EVENT_CS_EMPTY.option1.DESC = "option1%s"
EVENT_CS_EMPTY.option2.DESC = "option2%s"
EVENT_CS_EMPTY.option3.DESC = "option3%s"

EVENT_CS_KAOHE.TITLE = "EVENT_CS_KAOHE.TITLE"
EVENT_CS_KAOHE.DESC = "EVENT_CS_KAOHE.DESC"
EVENT_CS_KAOHE.option1.DESC = "option1"

EVENT_PROV_HONG_START.TITLE = "EVENT_PROV_HONG_START.TITLE"
EVENT_PROV_HONG_START.DESC = "EVENT_PROV_HONG_START.DESC"
EVENT_PROV_HONG_START.option1.DESC = "option1"

EVENT_PROV_HONG_END.TITLE = "EVENT_PROV_HONG_END.TITLE"
EVENT_PROV_HONG_END.DESC = "EVENT_PROV_HONG_END.DESC"
EVENT_PROV_HONG_END.option1.DESC = "option1"

TABLE_KAOHE_COLUM={}
TABLE_KAOHE_COLUM.OFFICE = "OFFICE"
TABLE_KAOHE_COLUM.NAME = "NAME"
TABLE_KAOHE_COLUM.FACTION = "FACTION"
TABLE_KAOHE_COLUM.VALUE = "VALUE"

ZHOUJ = {}
ZHOUJ.Zhouj1 ="YouZ"
ZHOUJ.Zhouj2 ="JiZ"
ZHOUJ.Zhouj3 ="BingZ"
ZHOUJ.Zhouj4 ="YongZ"
ZHOUJ.Zhouj5 ="QingZ"
ZHOUJ.Zhouj6 ="YuZ"
ZHOUJ.Zhouj7 ="YiZ"
ZHOUJ.Zhouj8 ="YangZ"
ZHOUJ.Zhouj9 ="JingZ"
